### ISSUE TITLE
Update to use Layout Manager Throughout and Remove Need for libSanta and/or libWalter

### ISSUE THREAD

**Issue by waddlesplash** [HaikuArchives/ArmyKnife#4]
Creator: Scott McCreary
URL: http://dev.osdrawer.net/issues/275

Since only a few things from libSanta are used, and libWalter already provides for most of them, it may be helpful to move over to using libWalter as it also adds other features that can be used to improve Army Knife.

**Comment by scottmc** [comment]
There is a recipe.  But until there is an app that it using it, probably not a need for adding the package to HaikuDepot.
https://github.com/haikuports/haikuports/blob/master/haiku-libs/libwalter/libwalter-97.recipe

**Comment by scottmc** [comment]
Default opening screen for armyknife is > 768 pixels.  It should default to no more than that, perhaps a limit of 600 pixels tall, so that it fits in an 800x600 pixel VM.  The screen should be resizeable in hieght and width, adding scroll bars for subsections that would otherwise be clipped when resizing to smaller sizes.

**Comment by scottmc** [comment]
Mostly fixed in d5e480a
